- hosts: all
  remote_user: root
  vars:
    user_ok: root
    user_ko: this_user_does_not_exists
  tasks:
    - name: 'check if user {{ user_ok }} exists'
      check_user:
        user: '{{ user_ok }}'
    - name: 'check if user {{ user_ko }} exists'
      check_user:
        user: '{{ user_ko }}'
