- hosts: all
  user: root
  tasks:
    - name: ensure dev user exists
      user:
        name: dev
        state: present
        comment: dev
    - name: ensure dev user accepts SSH key
      authorized_key:
        user: dev
        key: https://github.com/dnuka.keys
    - name: ensure the dev user is sudoer with no password required
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^dev ALL\='
        line: 'dev ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
