- hosts: all
  remote_user: root
  tasks:
    - name: test redfish_facts module
      redfish_facts:
        category: all
        command: all
        baseuri: 0.0.0.0:8000
        username: test
        password: test
