- hosts: all
  remote_user: root
  tasks:
    - name: test redfish_facts module
      redfish_facts:
        category: ["Systems", "Accounts", "Update"]
        baseuri: http://127.0.0.1:8000/redfish/v1/Systems/1
