- hosts: all
  remote_user: root
  tasks:
    - name: test redfish_facts module
      redfish_facts:
        category: Manager
        command: all
        baseuri: http://127.0.0.1:8000/
        username: foo
        password: bar
