- hosts: all
  remote_user: root
  tasks:
    - name: test redfish_facts module
      redfish_facts:
        category: Systems
        command: GetCpuInventory
        baseuri: localhost:8000
        username: test
        password: test
